BeforeAll {
  $ModulePath = Join-Path $PSScriptRoot '..\scripts\lib\CustomData.psm1'
  Import-Module $ModulePath -Force
}

Describe 'custom-data file copying' {
  BeforeEach {
    $TestRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("rime-custom-data-test-" + [guid]::NewGuid().ToString('N'))
    $CustomRoot = Join-Path $TestRoot 'custom-data'
    $OutputRoot = Join-Path $TestRoot 'output-data'
    New-Item -ItemType Directory -Path (Join-Path $CustomRoot 'tools\data') -Force | Out-Null
    New-Item -ItemType Directory -Path $OutputRoot -Force | Out-Null
  }

  AfterEach {
    if (Test-Path -LiteralPath $TestRoot) {
      Remove-Item -LiteralPath $TestRoot -Recurse -Force
    }
  }

  It 'skips unresolved custom-data symlinks instead of failing the package' {
    $linkPath = Join-Path $CustomRoot 'tools\data\zrmdb.txt'
    $link = [pscustomobject]@{
      FullName = $linkPath
      Attributes = [System.IO.FileAttributes]::ReparsePoint
      Target = '..\..\lua\zrmdb.txt'
    }

    $result = Copy-PackCustomDataFile -File $link -CustomRoot $CustomRoot -OutputData $OutputRoot

    $result | Should -BeNullOrEmpty
    Test-Path -LiteralPath (Join-Path $OutputRoot 'tools\data\zrmdb.txt') | Should -BeFalse
  }

  It 'materializes resolvable custom-data symlinks as regular packaged files' {
    $targetDir = Join-Path $CustomRoot 'lua'
    New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    $targetPath = Join-Path $targetDir 'zrmdb.txt'
    Set-Content -LiteralPath $targetPath -Value 'resolved-content' -NoNewline -Encoding UTF8

    $linkPath = Join-Path $CustomRoot 'tools\data\zrmdb.txt'
    $link = [pscustomobject]@{
      FullName = $linkPath
      Attributes = [System.IO.FileAttributes]::ReparsePoint
      Target = '..\..\lua\zrmdb.txt'
    }

    $result = Copy-PackCustomDataFile -File $link -CustomRoot $CustomRoot -OutputData $OutputRoot

    $result | Should -Be 'tools/data/zrmdb.txt'
    Get-Content -LiteralPath (Join-Path $OutputRoot 'tools\data\zrmdb.txt') -Raw | Should -Be 'resolved-content'
  }

  It 'builds missing OpenCC ocd2 dictionaries referenced by custom configs' {
    $openccRoot = Join-Path $OutputRoot 'opencc'
    New-Item -ItemType Directory -Path $openccRoot -Force | Out-Null
    [System.IO.File]::WriteAllText((Join-Path $openccRoot 'moran_t2s.json'), @'
{
  "conversion_chain": [{
    "dict": {
      "type": "group",
      "dicts": [{
        "type": "text",
        "file": "moran_TSPhrases.txt"
      }, {
        "type": "ocd2",
        "file": "moran_TSCharacters.ocd2"
      }]
    }
  }]
}
'@, [System.Text.UTF8Encoding]::new($false))
    Set-Content -LiteralPath (Join-Path $openccRoot 'moran_TSCharacters.txt') -Value "後`t后" -Encoding UTF8

    $openccDict = Join-Path $TestRoot 'opencc_dict.cmd'
    Set-Content -LiteralPath $openccDict -Encoding ASCII -Value @'
@echo off
set "out="
:loop
if "%~1"=="" goto done
if "%~1"=="-o" set "out=%~2"
shift
goto loop
:done
if "%out%"=="" exit /b 2
> "%out%" echo compiled
exit /b 0
'@

    $generated = @(Convert-PackCustomOpenCcTextDictionaries -OutputData $OutputRoot -OpenCcDictPath $openccDict)

    $generated.Count | Should -Be 1
    $generated[0] | Should -Be 'opencc/moran_TSCharacters.ocd2'
    Test-Path -LiteralPath (Join-Path $openccRoot 'moran_TSCharacters.ocd2') | Should -BeTrue
  }

  It 'runs known custom-data generators before OpenCC compilation' {
    New-Item -ItemType Directory -Path (Join-Path $OutputRoot 'tools'),(Join-Path $OutputRoot 'lua'),(Join-Path $OutputRoot 'opencc') -Force | Out-Null
    foreach ($script in @('gen_chars.py', 'gen_zrmdb.py', 'gen_chaifen_filter.py')) {
      Set-Content -LiteralPath (Join-Path $OutputRoot "tools\$script") -Value '# generated by test' -Encoding ASCII
    }

    $python = Join-Path $TestRoot 'python.cmd'
    Set-Content -LiteralPath $python -Encoding ASCII -Value @'
@echo off
for %%F in ("%~1") do set "script=%%~nxF"
if "%script%"=="gen_chars.py" echo chars-dict
if "%script%"=="gen_zrmdb.py" echo zrmdb-data
if "%script%"=="gen_chaifen_filter.py" echo chaifen-data
exit /b 0
'@

    $generated = @(Invoke-PackCustomDataGenerators -OutputData $OutputRoot -PythonPath $python)

    $generated | Should -Contain 'moran.chars.dict.yaml'
    $generated | Should -Contain 'lua/zrmdb.txt'
    $generated | Should -Contain 'opencc/moran_chaifen.txt'
    Get-Content -LiteralPath (Join-Path $OutputRoot 'moran.chars.dict.yaml') -Raw | Should -BeLike '*chars-dict*'
    Get-Content -LiteralPath (Join-Path $OutputRoot 'lua\zrmdb.txt') -Raw | Should -BeLike '*zrmdb-data*'
    Get-Content -LiteralPath (Join-Path $OutputRoot 'opencc\moran_chaifen.txt') -Raw | Should -BeLike '*chaifen-data*'
  }

  It 'keeps transitive schema and dictionary dependencies when pruning top-level data files' {
    Set-Content -LiteralPath (Join-Path $OutputRoot 'moran.schema.yaml') -Encoding UTF8 -Value @'
schema:
  schema_id: moran
  dependencies:
    - stroke
    - cangjie5
    - bopomofo
translator:
  dictionary: moran.extended
'@
    Set-Content -LiteralPath (Join-Path $OutputRoot 'moran.extended.dict.yaml') -Encoding UTF8 -Value @'
---
name: moran.extended
import_tables:
  - moran.chars
...
'@
    foreach ($file in @(
      'moran.chars.dict.yaml',
      'stroke.schema.yaml',
      'stroke.dict.yaml',
      'cangjie5.schema.yaml',
      'cangjie5.dict.yaml',
      'bopomofo.schema.yaml',
      'terra_pinyin.dict.yaml'
    )) {
      Set-Content -LiteralPath (Join-Path $OutputRoot $file) -Value 'fixture' -Encoding UTF8
    }
    Set-Content -LiteralPath (Join-Path $OutputRoot 'bopomofo.schema.yaml') -Encoding UTF8 -Value @'
schema:
  schema_id: bopomofo
translator:
  dictionary: terra_pinyin
'@

    $keep = @(Get-PackRequiredTopLevelDataBasenames -OutputData $OutputRoot -SeedBasenames @('moran.schema.yaml'))

    $keep | Should -Contain 'moran.schema.yaml'
    $keep | Should -Contain 'moran.extended.dict.yaml'
    $keep | Should -Contain 'moran.chars.dict.yaml'
    $keep | Should -Contain 'stroke.schema.yaml'
    $keep | Should -Contain 'stroke.dict.yaml'
    $keep | Should -Contain 'cangjie5.schema.yaml'
    $keep | Should -Contain 'cangjie5.dict.yaml'
    $keep | Should -Contain 'bopomofo.schema.yaml'
    $keep | Should -Contain 'terra_pinyin.dict.yaml'
  }
}
