#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir = Split-Path -Parent (Split-Path -Parent $PSCommandPath)
Import-Module (Join-Path $ScriptDir 'scripts\lib\Toolchain.psm1') -Force

$BoostRoot = Join-Path $ScriptDir 'boost_1_84_0'
$WeaselRepo = Join-Path $ScriptDir 'weasel'
$MsvcToolsVersion = $env:PACK_MSVC_TOOLS_VERSION
$SdkVer = $env:PACK_SDK_VERSION

function Require-Path([string]$Path, [string]$Name) {
    if (-not (Test-Path -LiteralPath $Path)) {
        throw "$Name not found: $Path"
    }
}

function Find-VsDevCmd {
    $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
    Require-Path $vswhere 'Visual Studio Installer vswhere.exe'

    $instPath = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath 2>$null
    if (-not $instPath) {
        throw "No Visual Studio install with C++ toolset found."
    }

    $candidate = Join-Path $instPath 'Common7\Tools\VsDevCmd.bat'
    Require-Path $candidate 'VsDevCmd.bat'
    return $candidate
}

function Detect-LatestSdk {
    $sdkRoot = "${env:ProgramFiles(x86)}\Windows Kits\10\Include"
    Require-Path $sdkRoot 'Windows SDK Include directory'

    $versions = Get-ChildItem -LiteralPath $sdkRoot -Directory |
        Where-Object { $_.Name -match '^10\.\d+\.\d+\.\d+$' } |
        Sort-Object { [Version]$_.Name } -Descending
    if (-not $versions) {
        throw "No Windows SDK versions found under $sdkRoot."
    }
    return $versions[0].Name
}

function Write-WeaselEnvBat([string]$Root) {
    $envBat = Join-Path $Root 'env.bat'
    [System.IO.File]::WriteAllLines(
        $envBat,
        [string[]]@(
            'rem Generated by prepare-boost.ps1 - defaults only apply when not already set by the caller.',
            'if not defined BOOST_ROOT set BOOST_ROOT=C:\Libraries\boost_1_78_0'
        ),
        [System.Text.Encoding]::ASCII
    )
}

Require-Path $BoostRoot 'Boost root'
Require-Path (Join-Path $BoostRoot 'boost') 'Boost headers'
Require-Path (Join-Path $WeaselRepo 'build.bat') 'weasel\build.bat'

$missingBoost = @(Get-MissingBoostLibraries $BoostRoot)
if ($missingBoost.Count -eq 0) {
    Write-Host 'Boost static libraries already prepared.'
    exit 0
}

$VsDevCmd = Find-VsDevCmd
if (-not $SdkVer) {
    $SdkVer = Detect-LatestSdk
}
$toolset = Get-DefaultToolsetForVsDevCmd $VsDevCmd
$PlatformToolset = $toolset.Platform
$BjamToolset = $toolset.Bjam

Write-Host 'Preparing Boost static libraries for cache...'
Write-Host "  missing: $($missingBoost -join ', ')"
Write-Host "  Boost root: $BoostRoot"
Write-Host "  Weasel    : $WeaselRepo"
Write-Host "  SDK       : $SdkVer"
Write-Host "  Toolset   : $PlatformToolset ($BjamToolset)"
Write-WeaselEnvBat $WeaselRepo

$boostArchitectures = @(Get-BoostBuildArchitectures)
$bootstrapArch = $boostArchitectures[0]
$boostBootstrapVsDevCmdCall = New-VsDevCmdCall `
    -VsDevCmd $VsDevCmd `
    -MsvcToolsVersion $MsvcToolsVersion `
    -Architecture $bootstrapArch.VsArchitecture `
    -HostArchitecture $bootstrapArch.HostArchitecture

$boostBootstrapCmd = "$boostBootstrapVsDevCmdCall && cd /d `"$BoostRoot`" && call bootstrap.bat vc143"
& cmd.exe /d /s /c $boostBootstrapCmd
if ($LASTEXITCODE -ne 0) {
    throw "Boost bootstrap failed with exit code $LASTEXITCODE"
}

foreach ($boostArch in $boostArchitectures) {
    $archMissing = @(Get-BoostLinkLibraries $boostArch.Architecture | Where-Object {
        -not (Test-Path -LiteralPath (Join-Path $BoostRoot "stage\lib\$_"))
    })
    if ($archMissing.Count -eq 0) {
        Write-Host "  Boost $($boostArch.Architecture): already prepared."
        continue
    }

    $boostVsDevCmdCall = New-VsDevCmdCall `
        -VsDevCmd $VsDevCmd `
        -MsvcToolsVersion $MsvcToolsVersion `
        -Architecture $boostArch.VsArchitecture `
        -HostArchitecture $boostArch.HostArchitecture

    $selectedCl = & cmd.exe /d /s /c "$boostVsDevCmdCall && where cl"
    $selectedClPath = Select-ClPath $selectedCl
    if ($LASTEXITCODE -ne 0 -or -not $selectedClPath) {
        throw "VsDevCmd did not expose cl.exe for Boost.Build $($boostArch.Architecture) configuration."
    }

    $boostProjectConfig = New-BoostProjectConfig $selectedClPath
    Set-Content -LiteralPath (Join-Path $BoostRoot 'project-config.jam') -Value $boostProjectConfig -Encoding ASCII
    Write-Host "  Boost.Build $($boostArch.Architecture): $boostProjectConfig"

    $bjamOptions = (Get-BoostBjamOptions -Architecture $boostArch.Architecture -BjamToolset $BjamToolset) -join ' '
    $cmd = "$boostVsDevCmdCall && set `"SDKVER=$SdkVer`" && set `"BOOST_ROOT=$BoostRoot`" && set `"PLATFORM_TOOLSET=$PlatformToolset`" && set `"BJAM_TOOLSET=$BjamToolset`" && cd /d `"$BoostRoot`" && b2.exe $bjamOptions stage"
    & cmd.exe /d /s /c $cmd
    if ($LASTEXITCODE -ne 0) {
        throw "Boost $($boostArch.Architecture) build failed with exit code $LASTEXITCODE"
    }
}

$missingBoost = @(Get-MissingBoostLibraries $BoostRoot)
if ($missingBoost.Count -gt 0) {
    throw "Boost static library preparation incomplete. Missing: $($missingBoost -join ', ')"
}

# These intermediates make the cache large and are not needed by pack.ps1 once stage\lib is complete.
$boostBin = Join-Path $BoostRoot 'bin.v2'
if (Test-Path -LiteralPath $boostBin) {
    Remove-Item -LiteralPath $boostBin -Recurse -Force
}

Write-Host 'Boost static libraries are ready for cache save.'
